### ISSUE TITLE
main project's wheel not being added to distribution or pex

### ISSUE THREAD

**Issue by sundaymtn** [linkedin/pygradle#127]
I have a pygradle project that builds/tests/runs successfully on linux but when I build it on windows the build/wheel-cache contains my main module's .whl and other dependent .whl's but the build/pex-cache never gets my module despite getting the others.  I think that's why the deployable reports an import error when calling them.
```
C:\Projects\workflow>git workflow.py -h
Traceback (most recent call last):
  File ".bootstrap\_pex\pex.py", line 324, in execute
  File ".bootstrap\_pex\pex.py", line 257, in _wrap_coverage
  File ".bootstrap\_pex\pex.py", line 289, in _wrap_profiling
  File ".bootstrap\_pex\pex.py", line 367, in _execute
  File ".bootstrap\_pex\pex.py", line 425, in execute_entry
  File ".bootstrap\_pex\pex.py", line 439, in execute_pkg_resources
  File ".bootstrap\pkg_resources\__init__.py", line 2386, in resolve
ImportError: No module named git_extend
```
 If I open the distribution I can see that my git_extend .whl isn't there compared to the linux build where it is there.
Windows git_extend missing from pex-cache etc
![pygradle_windows](https://cloud.githubusercontent.com/assets/3495129/23728302/1bc8e420-042a-11e7-9002-d84a2c99f274.png)
Linux git_extend present everywhere
![pygradle_linux](https://cloud.githubusercontent.com/assets/3495129/23728289/087186b6-042a-11e7-8936-62416f1dbecd.png)

**Comment by zvezdan** [comment]
This happens if you use pip-9.x.
Resolved in https://github.com/linkedin/pygradle/pull/136
Released as 0.5.2
