### ISSUE TITLE
Wheel dependencies with pivy-importer not supported yet?

### ISSUE THREAD

**Issue by aedancullen** [linkedin/pygradle#178]
Try running:

`java -jar pivy-importer-0.3.16-all.jar --repo repo opencv-python:3.4.0.12`

(opencv-python on PyPI has only .whl files available, not .tar.gz or .zip)
and observe:

`Exception in thread "main" java.lang.NullPointerException: Cannot get property 'url' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at com.linkedin.python.importer.deps.DependencyDownloader.downloadDependency(DependencyDownloader.groovy:65)
	at com.linkedin.python.importer.deps.DependencyDownloader$downloadDependency.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.linkedin.python.importer.deps.DependencyDownloader.download(DependencyDownloader.groovy:48)
	at com.linkedin.python.importer.ImporterCLI.main(ImporterCLI.java:65)
`

So there seems to be a problem when we don't have a typical archive download URL available (and only wheels)... is there any way we can get this to work?

**Comment by jmeekhof** [comment]
bump

**Comment by Turakar** [comment]
You have to specify the binary classifier, as detailed in #230. You can look that up on [PyPI](pypi.org).
