### ISSUE TITLE
[0.7.11] - > Task :python:installBuildRequirements FAILED

### ISSUE THREAD

**Issue by jaredsburrows** [linkedin/pygradle#214]
# Repro:
`$ gradlew clean build`

# Error:
```
> Task :python:installBuildRequirements FAILED
Error installing package using `[/Users/<>/repo/cs-interview-questions/python/build/venv/bin/python, /Users/<>/repo/cs-interview-questions/python/build/venv/bin/pip, install, --disable-pip-version-check, --no-deps, --upgrade, /Users/<>/.gradle/caches/modules-2/files-2.1/pypi/mccabe/0.5.2/14c5b2794cae2a723cdf4ce520c4e0d8cae62986/mccabe-0.5.2.tar.gz]`
Processing /Users/<>/.gradle/caches/modules-2/files-2.1/pypi/mccabe/0.5.2/14c5b2794cae2a723cdf4ce520c4e0d8cae62986/mccabe-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1w/20_t1jyx6ggfdscxxg8gq0gw0000gn/T/pip-3RHXIR-build/setup.py", line 57, in <module>
        'Topic :: Software Development :: Quality Assurance',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/<>/repo/cs-interview-questions/python/build/venv/lib/python2.7/site-packages/setuptools/dist.py", line 317, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/<>/repo/cs-interview-questions/python/build/venv/lib/python2.7/site-packages/setuptools/dist.py", line 372, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/<>/repo/cs-interview-questions/python/build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/<>/repo/cs-interview-questions/python/build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1118, in best_match
        return self.obtain(req, installer)
      File "/Users/<>/repo/cs-interview-questions/python/build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1130, in obtain
        return installer(requirement)
      File "/Users/<>/repo/cs-interview-questions/python/build/venv/lib/python2.7/site-packages/setuptools/dist.py", line 440, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/<>/repo/cs-interview-questions/python/build/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 668, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/1w/20_t1jyx6ggfdscxxg8gq0gw0000gn/T/pip-3RHXIR-build/


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':python:installBuildRequirements'.
> Failed to install mccabe-0.5.2. Please see above output for reason, or re-run your build using ``gradle -i build`` for additional logging.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
31 actionable tasks: 30 executed, 1 up-to-date
```

**Comment by jaredsburrows** [comment]
@zvezdan I had trouble building with the latest version from my home computer. The previous version works fine.

**Comment by zvezdan** [comment]
@jaredsburrows It's one of those unpredictable transient errors in talking to PyPI. It seems to be happening more recently because of the transition from pypi.python.org to pypi.org (Warehouse).

There are ways to work around it.
For a small project, you can just add it into your dependencies under `setupRequires` configuration (not `python` runtime dependencies):
```
dependencies {
    setupRequires 'pypi:pytest-runner:2.9'
    // ...
}
```
That way Gradle will fetch it and install it, so `setuptools` will not need to contact PyPI for it.

For a larger project or group of projects you may want to build a small plugin that in its `apply` method has `project.plugins.apply(PythonPlugin)` to do standard pygradle application. Then you could add in the rest of that method.
```
import static com.linkedin.gradle.python.util.StandardTextValues.CONFIGURATION_SETUP_REQS
// ...
def pythonExtension = ExtensionUtils.getPythonExtension(project)
// ...
pythonExtension.forceVersion('pypi', 'pytest-runner', '2.9')
// ...
project.dependencies.add(CONFIGURATION_SETUP_REQS.getValue(), pythonExtension.forcedVersions['pytest-runner'])
// ...
```
That way your plugin controls this automatically for all your projects/users.

**Comment by zvezdan** [comment]
See my suggestion about `setupRequires` above @anjaneyulu1989 please.

We also added pytest-runner-2.9 and setuptools-scm-1.15.5 to our pypi-external repo which should help as well.

Due to the move of PyPI from pypi.python.org to pypi.org, though, we'll also go through the code and release a new version with that URL corrected.

**Comment by yasz** [comment]
@zvezdan  please help to rename setuptools_scm-1.15.5.tar.gz  to  setuptools-scm-1.15.5.tar.gz in linkedin jfrog. Thank you!

**Comment by anjaneyulu1989** [comment]
Hi @zvezdan , No luck even after adding the following, Is there anything am missing here.

`dependencies {
    setupRequires 'pypi:pytest-runner:2.9'
    // ...
}`

![image](https://user-images.githubusercontent.com/8857139/49300737-ce0c5380-f477-11e8-8daf-30d9e9401504.png)

**Comment by zvezdan** [comment]
@maksimlikharev The artifact name is correct. The dependency asks for setuptools-scm and that will look into the Ivy file with that name. The Ivy file contains the correct name of the artifact:
```
<artifact name="setuptools_scm" ext="tar.gz" conf="default" type="tar.gz" />
```
Thus, Gradle is able to find the artifact. It's the same in our repo at LinkedIn and builds work just fine. Please, make sure to provide `setupRequires ...` dependency for setuptools-scm if you continue experiencing the issue with that package.

Also, both python tooling and PyGradle tolerate correctly both naming conventions and convert between them as needed.

**Comment by zvezdan** [comment]
@anjaneyulu1989 There are newer releases of PyGradle. Try 0.8.10 or 0.8.11 -- I'm sure they are available on plugins.gradle.org.
I'll release the latest in 0.9.x series in a couple of hours too.
