### ISSUE TITLE
Execution failed for task ':installPythonRequirements'. > Failed to install pytest-xdist-1.14. 

### ISSUE THREAD

**Issue by eagle-crisley** [linkedin/pygradle#222]
Just trying to run the example project, and I receive the following error:

> Execution failed for task ':installPythonRequirements'.
> Failed to install pytest-xdist-1.14. 

```
11:13:57.450 [LIFECYCLE] [org.gradle.api.Task] Processing /Users/adc1blz/.gradle/caches/modules-2/files-2.1/pypi/pytest-xdist/1.14/d1920596e4780427656cb3e3c770333a803feae4/pytest-xdist-1.14.zip
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools_scm/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/setuptools-scm/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    No local packages or download links found for setuptools-scm
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/jp/wk7_c7px34x7x1g60sfh_l8h6vk8x9/T/pip-De92aO-build/setup.py", line 36, in <module>
        'Programming Language :: Python :: 3',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/adc1blz/Documents/GitHub/eagle-py-framework/build/venv/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/adc1blz/Documents/GitHub/eagle-py-framework/build/venv/lib/python2.7/site-packages/setuptools/dist.py", line 312, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/adc1blz/Documents/GitHub/eagle-py-framework/build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/adc1blz/Documents/GitHub/eagle-py-framework/build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1091, in best_match
        return self.obtain(req, installer)
      File "/Users/adc1blz/Documents/GitHub/eagle-py-framework/build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1103, in obtain
        return installer(requirement)
      File "/Users/adc1blz/Documents/GitHub/eagle-py-framework/build/venv/lib/python2.7/site-packages/setuptools/dist.py", line 379, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/adc1blz/Documents/GitHub/eagle-py-framework/build/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 633, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/jp/wk7_c7px34x7x1g60sfh_l8h6vk8x9/T/pip-De92aO-build
11:13:57.450 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Execute pipInstall for :installPythonRequirements'
11:13:57.450 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
11:13:57.450 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':installPythonRequirements'
11:13:57.450 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Task :installPythonRequirements'
11:13:57.450 [null] [org.gradle.internal.progress.DefaultBuildOperationExecutor] 
11:13:57.450 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Task :installPythonRequirements' completed
11:13:57.450 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :installPythonRequirements (Thread[Task worker for ':',5,main]) completed. Took 0.861 secs.
11:13:57.451 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.9 completed (1 worker(s) in use)
11:13:57.451 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': released lock on root.1.9
11:13:57.451 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Task worker for ':': released lock on :
11:13:57.451 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':',5,main]] finished, busy: 0.926 secs, idle: 0.008 secs
11:13:57.451 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 3,5,main]] finished, busy: 0.0 secs, idle: 0.932 secs
11:13:57.451 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 2,5,main]] finished, busy: 0.0 secs, idle: 0.933 secs
11:13:57.451 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Task worker for ':' Thread 3,5,main]] finished, busy: 0.0 secs, idle: 0.932 secs
11:13:57.451 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
11:13:57.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:13:57.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:13:57.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
11:13:57.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
11:13:57.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':installPythonRequirements'.
11:13:57.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Failed to install pytest-xdist-1.14. Please see above output for reason, or re-run your build using ``ligradle -i build`` for additional logging.
11:13:57.453 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 

```

**Comment by kopy07** [comment]
Thanks! @eagle-crisley. Let me take a look.

**Comment by maksimlikharev** [comment]
I have similar issues, 

`Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!`

very much could be related to changing the URL from pypi.python.org to pypi.org

**Comment by zvezdan** [comment]
See my comments and suggestions on #214 please.
We also added pytest-runner-2.9 and setuptools-scm-1.15.5 to our pypi-external repo which should help as well.

Due to the move of PyPI from pypi.python.org to pypi.org, though, we'll also go through the code and release a new version with that URL corrected.

**Comment by maksimlikharev** [comment]
yes, I tried #214, but pytest-runner-2.9 wasn't in the linkedin  pypi-external repo, will try again.
as far as I understand, pypi.python.org will stop working altogether on Mon or Tue.

**Comment by zvezdan** [comment]
@maksimlikharev Right, I just submitted a PR for upgrade of pypi URL: #224

**Comment by zvezdan** [comment]
@maksimlikharev I just released pygradle-0.7.16

**Comment by maksimlikharev** [comment]
thank you for the quick turn around.

**Comment by eagle-crisley** [comment]
I'm actually still running into the original issue: 
```
crisley2-mbp:test-pygradle adc1blz$ ./gradlew build
:pinRequirements
:createVirtualEnvironment
New python executable in /Users/adc1blz/Desktop/Work/test-pygradle/build/venv/bin/python
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /usr/bin/python2.7
:installLinks
:installSetupRequirements
Install setuptools-19.1.1 ........................................... [STARTING]
Install setuptools-19.1.1 (0:01 s) .................................. [FINISHED]
Install wheel-0.26.0 ................................................ [STARTING]
Install wheel-0.26.0 (0:01 s) ....................................... [FINISHED]
Install pip-7.1.2 ................................................... [STARTING]
Install pip-7.1.2 (0:04 s) .......................................... [FINISHED]
Install setuptools-git-1.1 .......................................... [STARTING]
Install setuptools-git-1.1 (0:01 s) ................................. [FINISHED]
Install pbr-1.8.0 ................................................... [STARTING]
Install pbr-1.8.0 (0:01 s) .......................................... [FINISHED]
Install argparse-1.4.0 .............................................. [STARTING]
Install argparse-1.4.0 (0:01 s) ..................................... [FINISHED]
:installBuildRequirements
Install Babel-1.3 ................................................... [STARTING]
Install Babel-1.3 (0:05 s) .......................................... [FINISHED]
Install Jinja2-2.3 .................................................. [STARTING]
Install Jinja2-2.3 (0:01 s) ......................................... [FINISHED]
Install Pygments-2.0 ................................................ [STARTING]
Install Pygments-2.0 (0:03 s) ....................................... [FINISHED]
Install Sphinx-1.4.1 ................................................ [STARTING]
Install Sphinx-1.4.1 (0:05 s) ....................................... [FINISHED]
Install alabaster-0.7.1 ............................................. [STARTING]
Install alabaster-0.7.1 (0:01 s) .................................... [FINISHED]
Install colorama-0.3.5 .............................................. [STARTING]
Install colorama-0.3.5 (0:01 s) ..................................... [FINISHED]
Install docutils-0.11 ............................................... [STARTING]
Install docutils-0.11 (0:03 s) ...................................... [FINISHED]
Install flake8-2.5.4 ................................................ [STARTING]
Install flake8-2.5.4 (0:01 s) ....................................... [FINISHED]
Install imagesize-0.7.1 ............................................. [STARTING]
Install imagesize-0.7.1 (0:01 s) .................................... [FINISHED]
Install mccabe-0.2.1 ................................................ [STARTING]
Install mccabe-0.2.1 (0:01 s) ....................................... [FINISHED]
Install pep8-1.5.7 .................................................. [STARTING]
Install pep8-1.5.7 (0:01 s) ......................................... [FINISHED]
Install pyflakes-0.8.1 .............................................. [STARTING]
Install pyflakes-0.8.1 (0:01 s) ..................................... [FINISHED]
Install pytz-2016.4 ................................................. [STARTING]
Install pytz-2016.4 (0:04 s) ........................................ [FINISHED]
Install six-1.10.0 .................................................. [STARTING]
Install six-1.10.0 (0:01 s) ......................................... [FINISHED]
Install snowballstemmer-1.1.0 ....................................... [STARTING]
Install snowballstemmer-1.1.0 (0:01 s) .............................. [FINISHED]
:installPythonRequirements
Install requests-2.9.1 .............................................. [STARTING]
Install requests-2.9.1 (0:02 s) ..................................... [FINISHED]
:installTestRequirements
Install argparse-1.4.0 .............................................. [SKIPPING]
Install colorama-0.3.7 .............................................. [STARTING]
Install colorama-0.3.7 (0:01 s) ..................................... [FINISHED]
Install coverage-3.7.1 .............................................. [STARTING]
Install coverage-3.7.1 (0:03 s) ..................................... [FINISHED]
Install funcsigs-1.0.2 .............................................. [STARTING]
Install funcsigs-1.0.2 (0:01 s) ..................................... [FINISHED]
Install mock-1.3.0 .................................................. [STARTING]
Install mock-1.3.0 (0:01 s) ......................................... [FINISHED]
Install ordereddict-1.1 ............................................. [STARTING]
Install ordereddict-1.1 (0:00 s) .................................... [FINISHED]
Install pbr-1.8.0 ................................................... [SKIPPING]
Install py-1.4.29 ................................................... [STARTING]
Install py-1.4.29 (0:01 s) .......................................... [FINISHED]
Install pytest-cov-2.2.1 ............................................ [STARTING]
Install pytest-cov-2.2.1 (0:01 s) ................................... [FINISHED]
Install pytest-xdist-1.14 ........................................... [STARTING]
Processing /Users/user/.gradle/caches/modules-2/files-2.1/pypi/pytest-xdist/1.14/d1920596e4780427656cb3e3c770333a803feae4/pytest-xdist-1.14.zip
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools_scm/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/setuptools-scm/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) -- Some packages may not be found!
    No local packages or download links found for setuptools-scm
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/jp/wk7_c7px34x7x1g60sfh_l8h6vk8x9/T/pip-M2rr16-build/setup.py", line 36, in <module>
        'Programming Language :: Python :: 3',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/adc1blz/Desktop/Work/test-pygradle/build/venv/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/adc1blz/Desktop/Work/test-pygradle/build/venv/lib/python2.7/site-packages/setuptools/dist.py", line 312, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/adc1blz/Desktop/Work/test-pygradle/build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/adc1blz/Desktop/Work/test-pygradle/build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1091, in best_match
        return self.obtain(req, installer)
      File "/Users/adc1blz/Desktop/Work/test-pygradle/build/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1103, in obtain
        return installer(requirement)
      File "/Users/adc1blz/Desktop/Work/test-pygradle/build/venv/lib/python2.7/site-packages/setuptools/dist.py", line 379, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/adc1blz/Desktop/Work/test-pygradle/build/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 633, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-scm')
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/jp/wk7_c7px34x7x1g60sfh_l8h6vk8x9/T/pip-M2rr16-build
:installTestRequirements FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installTestRequirements'.
> Failed to install pytest-xdist-1.14. Please see above output for reason, or re-run your build using ``ligradle -i build`` for additional logging.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by kontact-chan** [comment]
setuptools_scm and setuptools-scm
It is the _ and - confusion. Can someone please fix this?

https://linkedin.jfrog.io/linkedin/pypi-external/pypi/setuptools-scm/1.15.5/

setuptools-scm-1.15.5.ivy      27-Apr-2018 22:37  588 bytes
setuptools_scm-1.15.5.tar.gz   27-Apr-2018 22:37  25.15 KB

Here is the error:
* What went wrong:
Execution failed for task ':cassandra_python:installSetupRequirements'.
> Could not resolve all files for configuration ':cassandra_python:setupRequires'.
   > Could not find setuptools-scm.tar.gz (pypi:setuptools-scm:1.15.5).
     Searched in the following locations:
         https://linkedin.jfrog.io/linkedin/pypi-external/pypi/setuptools-scm/1.15.5/setuptools-scm-1.15.5.tar.gz

The correct name should be setuptools_scm, looks like.

**Comment by zvezdan** [comment]
@kontact-chan We fixed the Ivy metadata.
