### ISSUE TITLE
how can i specify using default python3

### ISSUE THREAD

**Issue by yasz** [linkedin/pygradle#234]
I have both python2 and python3 , how can I specify use python3 when I invoke gradle build?
os & python:
```
redhat 7.4
python2.7.5
python3.6.5
```

build & invoke message
`/opt/dev/build/venv/bin/hello_world`
`print(sys.path)`

> ['/opt/dev/build/venv/bin', '/opt/dev/build/venv/lib64/python27.zip', '/opt/dev/build/venv/lib64/python2.7', '/opt/dev/build/venv/lib64/python2.7/plat-linux2', '/opt/dev/build/venv/lib64/python2.7/lib-tk', '/opt/dev/build/venv/lib64/python2.7/lib-old', '/opt/dev/build/venv/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7', '/usr/lib/python2.7', '/opt/dev/build/venv/lib/python2.7/site-packages', '/opt/dev/src']

**Comment by yasz** [comment]
Thank you , it solves my issue~

**Comment by smslack** [comment]
Where  is the python config block defined? Is it in the build.gradle file?

**Comment by smslack** [comment]
I keep getting this error while running the gradle build using pygradle:

Processing /tmp/pypi-local/pypi/Sphinx/1.8.1/Sphinx-1.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-Zb0QRr/setup.py", line 82, in <module>
        from babel.messages.pofile import read_po
      File "/home/smanda/stash/python_packaging_example_git/build/venv/local/lib/python2.7/site-packages/babel/messages/__init__.py", line 12, in <module>
        from babel.messages.catalog import *
      File "/home/python_packaging_example_git/build/venv/local/lib/python2.7/site-packages/babel/messages/catalog.py", line 23, in <module>
        from babel.dates import format_datetime
      File "/home/python_packaging_example_git/build/venv/local/lib/python2.7/site-packages/babel/dates.py", line 28, in <module>
        from babel.util import UTC, LOCALTZ
      File "/home/python_packaging_example_git/build/venv/local/lib/python2.7/site-packages/babel/util.py", line 282, in <module>
        UTC = _pytz.utc
    AttributeError: 'module' object has no attribute 'utc'

How do i fix this?
