### ISSUE TITLE
SdistDownloader assumes that all dependencies will also be an sdist

### ISSUE THREAD

**Issue by chrisbrake** [linkedin/pygradle#239]
https://github.com/linkedin/pygradle/blob/2246e4f9a3ba35a525d2e5fe59b7c88fcf6884e0/pivy-importer/src/main/groovy/com/linkedin/python/importer/deps/SdistDownloader.groovy#L38

**Comment by chrisbrake** [comment]
When trying to download Flask with this, in lenient mode, I ended up with these two errors.

```Unable to find source dist for pywin32:223
Unable to find source dist for pytest-pythonpath:0.7.2```

This is because they are only available as wheels

**Comment by Kindrat** [comment]
Same here. I'm working on a patch in my fork. So mb it would be available soon as PR

**Comment by umayrh** [comment]
Encountering the same issue when downloading `airflow`:

```
$ java -jar scripts/pivy-importer-0.9.9-all.jar --debug --repo build/local-ivy-repo 'PyYAML:3.10' 'apache-airflow:1.10.2' 'requests:2.21.0'
...
11:10:41.951 DEBUG c.l.p.i.distribution.PythonPackage - Split lineWithMarker[0] into conditions (itsdangerous>=0.21) [itsdangerous>=0.21]
11:10:41.951 DEBUG c.l.p.i.distribution.PythonPackage - Split condition into parts (itsdangerous>=0.21) [itsdangerous, 0.21]
Exception in thread "main" java.lang.RuntimeException: Unable to find source dist for PyYAML:3.01
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

@Kindrat Your fork fails to build:

```
> Configure project :pivy-importer
Evaluating project ':pivy-importer' using build file '/Users/umayrhassan/Code/pygradle/pivy-importer/build.gradle'.
Adding license extension
Adding download licenses extension
Adding license extension rule
Applying defaults to download task: :pivy-importer:downloadLicenses
Adding license tasks for sourceSet licenseMain
Applying license defaults to task: :pivy-importer:licenseMain
Applying license defaults to task: :pivy-importer:licenseFormatMain
Adding license tasks for sourceSet licenseTest
Applying license defaults to task: :pivy-importer:licenseTest
Applying license defaults to task: :pivy-importer:licenseFormatTest
Selected primary task 'build' from project :pivy-importer

FAILURE: Build failed with an exception.

* What went wrong:
Method com/github/jengelman/gradle/plugins/shadow/internal/DependencyFileCollection.getBuildDependencies()Lorg/gradle/api/tasks/TaskDependency; is abstract
```

**Comment by Kindrat** [comment]
@umayrh I'm not going support PR for a dead project. A bit tired of waiting for any response.

**Comment by Turakar** [comment]
This is actually still an issue as you can confirm by trying to import `tensorflow-gpu:1.13.1:cp37-cp37m-manylinux1_x86_64`. I think this should be re-opened.
