### ISSUE TITLE
Build issue with pygradle

### ISSUE THREAD

**Issue by smslack** [linkedin/pygradle#337]
I keep getting this error while running the gradle build using pygradle:

Processing /tmp/pypi-local/pypi/Sphinx/1.8.1/Sphinx-1.8.1.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-req-build-Zb0QRr/setup.py", line 82, in
from babel.messages.pofile import read_po
File "/home/python_packaging_example_git/build/venv/local/lib/python2.7/site-packages/babel/messages/init.py", line 12, in
from babel.messages.catalog import *
File "/home/python_packaging_example_git/build/venv/local/lib/python2.7/site-packages/babel/messages/catalog.py", line 23, in
from babel.dates import format_datetime
File "/home/python_packaging_example_git/build/venv/local/lib/python2.7/site-packages/babel/dates.py", line 28, in
from babel.util import UTC, LOCALTZ
File "/home/python_packaging_example_git/build/venv/local/lib/python2.7/site-packages/babel/util.py", line 282, in
UTC = _pytz.utc
AttributeError: 'module' object has no attribute 'utc'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installBuildRequirements'.

How do i fix this?

Also i see that it is using python version 2.7 in the virtualenv, how do i specify to use python 3.6 instead?

**Comment by shvilime** [comment]
To use python version 3.6, you can set this in your build.gradle.
`
python {
     details {
        virtualEnvPrompt = "(${project.name})"
        activateLink = project.file("activate")
        pinnedFile = project.file('requirements.txt')
        details.pythonVersion = '3.7'
     }
}
`
