### ISSUE TITLE
Plugin works on command line but fails with python not found in eclipse and idea

### ISSUE THREAD

**Issue by PeterLappo** [linkedin/pygradle#55]
Hi, 
I'm using Mac El Cap - Latest Idea or latest eclipse and gradlew using 3.1 with plugin id "com.linkedin.python-sdist" version "0.3.20". Config is a copy of the example more or less.
Most strange can't find /usr/bin/python. 
systemPythonInterpreter override made no difference.
Works perfectly in terminal window.

Any ideas?
Other than that a great plugin.
Peter
`
Unable to find or execute python
....
Caused by: java.lang.RuntimeException: Unable to find or execute python
	at com.linkedin.gradle.python.extension.PythonDetails.updateFromPythonInterpreter(PythonDetails.java:48)
	at com.linkedin.gradle.python.extension.PythonDetails.setPythonVersion(PythonDetails.java:111)
	at build_5kainnwc1tl7krk6rw33j2pjw$_run_closure2$_closure5.doCall(linkedin/build.gradle:31)
	at build_5kainnwc1tl7krk6rw33j2pjw$_run_closure2$_closure5.doCall(linkedin/build.gradle)
	at com.linkedin.gradle.python.PythonExtension.details(PythonExtension.groovy:140)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
`

**Comment by PeterLappo** [comment]
aha, this works, would be nice if it printed $PATH if it failed to find python
        //pythonVersion = '3,3' // Sets the version of python to use, will search your PATH to get the location
        systemPythonInterpreter = file("/usr/local/bin/python3.3") // used to force an interpreter to be used to build the venv
